### PR TITLE
Moving stuff around

### PR DESCRIPTION
**Pull request by sgoodlett**
Hey it worked! You might want to check if I broke stuff, because I probably did...

### CODE REVIEW

**Comment by sgoodlett** [comment]
@nlk36701 You may want to rename "Salcs.jl" to something else if we are naming the module SALCs. It is a little confusing. I usually like naming a file like that "Main.jl"

**Comment by sgoodlett** [comment]
Also, you will need to update your Project.toml file so that Molecules.jl v0.3.0 is supported

**Comment by sgoodlett** [comment]
Also, also, dependency on StaticArrays and ForwardDiff are needed so that things work. This should be fixed as soon as Gustavo's code is merged.

**Comment by sgoodlett** [comment]
Also, also, also, there are many problems that need to be fixed, but we can wait til Gustavo's PR is done. So we won't worry about that for now

**Review by nlk36701 — APPROVED** [review]

**Pull request merged**
